version: 2.1

defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:1
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  working_directory: ~/build

aliases:
  - &restore-cache-grails
    keys:
      - v1-oci-test-grails-{{ .Branch }}-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
      - v1-oci-test-grails-{{ .Branch }}
      - v1-oci-test-grails
  - &save-cache-grails
    key: v1-oci-test-grails-{{ .Branch }}-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
    paths:
      - ~/.m2/repository

jobs:
  inject-environment:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:1
    steps:
      - run: circle_ci_add_env.sh \
          DOCKER_USER DOCKER_PASS \
          MAVEN_REPO JFROG_USER JFROG_PASSWD \
          CIRCLE_CI_TOKEN \
          SSH_KEY DOCUMENTATION_STORAGE_HOST
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-grails
      - run:
          name: Refresh dependencies
          command: grails refresh-dependencies --non-interactive
      - run:
          name: Build and deploy artifact
          command: grails maven-deploy -Dgrails.env=prod -verbose
      - save_cache: *save-cache-grails
      - setup_remote_docker
      - run:
          name: Build and deploy docker image
          command: |
            ./build/docker/application/bin/build.sh --jfrog-token="$JFROG_PASSWD" --docker-user="$DOCKER_USER" --docker-pass="$DOCKER_PASS"
            ./build/docker/application/bin/push.sh --docker-user="$DOCKER_USER" --docker-pass="$DOCKER_PASS"

workflows:
  version: 2
  build:
    jobs:
      - inject-environment:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - inject-environment
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
