version: 2

aliases:
  - &inject-environment
    name: Inject environment
    command: /bin/env_inject.sh

  - &restore-cache
    keys:
      - v1-{{ checksum "package.json" }}

  - &save-cache
    key: v1-{{ checksum "package.json" }}
    paths:
      - ./node_modules

defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:grails-2.4.4-jdk-8u131-nodejs-6.9.4-maven-3.3.9
      auth:
        username: ${DOCKER_USER}
        password: ${DOCKER_PASS}
  working_directory: ~/build

jobs:
  inject-environment:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:1
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: |
            circle_ci_add_env.sh \
              DOCKER_USER DOCKER_PASS \
              GH_NAME GH_MAIL \
              MAVEN_REPO JFROG_USER JFROG_PASSWD \
              CIRCLE_CI_TOKEN \
              SSH_KEY DOCUMENTATION_STORAGE_HOST
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: 
          name: Build oci-test
          command: clean war:war
workflows:
  version: 2
  build-and-deploy-to-cloud:
    jobs:
      - inject-environment
      - build:
	  requires:
            - inject-environment
