version: 2

aliases:
  - &inject-environment
    name: Inject environment
    command: /bin/env_inject.sh

  - &restore-cache
    keys:
      - v1-{{ checksum "package.json" }}

  - &save-cache
    key: v1-{{ checksum "package.json" }}
    paths:
      - ./node_modules

defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:grails-2.4.4-jdk-8u131-nodejs-6.9.4-maven-3.3.9
  working_directory: ~/build

jobs:
  build:
    <<: *defaults
    steps:
      - run: *inject-environment
      - checkout
      - restore_cache: *restore-cache
      - run: 
          name: Build oci-test
          command: clean war:war
workflows:
  version: 2
  build-and-deploy-to-cloud:
    jobs:
      - build