version: 2.1

defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:1
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  working_directory: ~/build

aliases:
  - &restore-cache-grails
    keys:
      - v1-oci-test-{{ .Branch }}-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
      - v1-oci-test-{{ .Branch }}
      - v1-oci-test
  - &save-cache-grails
    key: v1-oci-test-{{ .Branch }}-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
    paths:
      - ~/.m2/repository

jobs:
  inject-environment:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:1
    steps:
      - run: circle_ci_add_env.sh \
          DOCKER_USER DOCKER_PASS \
          MAVEN_REPO JFROG_USER JFROG_PASSWD \
          CIRCLE_CI_TOKEN
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-grails
      - run:
          name: Refresh dependencies
          command: grails refresh-dependencies --non-interactive
      - run:
          name: Build and deploy artifact
          command: grails maven-deploy -Dgrails.env=prod -verbose
      - save_cache: *save-cache-grails

workflows:
  version: 2
  build:
    jobs:
      - inject-environment:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - inject-environment
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
